/*
 * Q3-1 (1)원자성 (2)완전 함수적 종속 (3)이행적 종속 제거
 * Q3-2 (1)제3정규화(3NF) (2)제2정규화(2NF)
 * Q3-3 (1)inner join (2)left join (3)right join (4)outer join
 * Q3-4 (1)반정규화(Denormalization)
 * Q3-5 (1)인덱스(Index) (2)인덱스 (3)인덱스 (4)인덱스
 * Q3-6 (1)트랜잭션(Transaction) (2)Atomicity(원자성) (3)Consistency(일관성) 
 * 
 */


--1-1
CREATE TABLE DEPT_TEST
	AS (SELECT * FROM DEPT)
	;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
	VALUES (50, 'ORACLE', 'BUSAN')
	;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
	VALUES (60, 'SQL', 'ILSAN')
	;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
	VALUES (70, 'SELECT', 'INCHEON')
	;
INSERT INTO DEPT_TEST (DEPTNO, DNAME, LOC)
	VALUES (80, 'DML', 'BUNDANG')
	;
SELECT * FROM DEPT_TEST;



--1-2
DROP TABLE emp_test;

CREATE TABLE EMP_TEST
	AS (SELECT * 
		FROM EMP 
		WHERE 1<>1)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7201, 'TEST_USER1', 'MANAGER', 7788, 
			TO_DATE('2016/01/02', 'YYYY/MM/DD'), 4500)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7202, 'TEST_USER2', 'CLERK', 7201, 
			TO_DATE('2016/02/21', 'YYYY/MM/DD'), 1800)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7203, 'TEST_USER3', 'ANALYST', 7201, 
			TO_DATE('2016/04/11', 'YYYY/MM/DD'), 3400)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7204, 'TEST_USER4', 'SALESMAN', 7201, 
			TO_DATE('2016/05/31', 'YYYY/MM/DD'), 2700)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7205, 'TEST_USER5', 'CLERK', 7201, 
			TO_DATE('2016/07/20', 'YYYY/MM/DD'), 2600)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7206, 'TEST_USER6', 'CLERK', 7201, 
			TO_DATE('2016/09/08', 'YYYY/MM/DD'), 2600)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7207, 'TEST_USER7', 'LECTURER', 7201, 
			TO_DATE('2016/10/28', 'YYYY/MM/DD'), 2300)
	;
INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
	VALUES (7208, 'TEST_USER8', 'STUDENT', 7201, 
			TO_DATE('2018/03/09', 'YYYY/MM/DD'), 1200)
	;

SELECT * FROM EMP_TEST


--1-3 -> 문제 오류??
UPDATE EMP_TEST
	SET DEPTNO = 70
	WHERE SAL > (SELECT AVG(SAL) 
				 FROM EMP_TEST 
				 WHERE DEPTNO = 50)
	;

--1-4 -> 문제 오류??
UPDATE EMP_TEST 
	SET DEPTNO = 80
	   ,SAL = SAL * 1.2
	WHERE EMPNO = (SELECT EMPNO 
				   FROM (SELECT EMPNO 
				         FROM EMP_TEST 
				         WHERE DEPTNO = 60
				         ORDER BY HIREDATE)
				   WHERE ROWNUM = 1)
;

-- 2-1

CREATE TABLE EMP_USER(
	EMPNO		NUMBER(4)
	,ENAME		VARCHAR2(10)
	,JOB			VARCHAR2(9)
	,MGR			NUMBER(4)
	,HIREDATE	DATE
	,SAL		NUMBER(7,2)
	,COMM		NUMBER(7,2)
	,DEPTNO		NUMBER(2)
)
;

-- 2-2
ALTER  TABLE EMP_USER
	ADD EMP_DATE     DATE
;

ALTER  TABLE EMP_USER
	ADD RESIGN_DATE     DATE
;


ALTER  TABLE EMP_USER (
	ADD EMP_DATE     DATE 
	,RESIGN_DATE     DATE
);


-- 2-3
ALTER TABLE EMP_USER 	
	ADD SUR_NAME	VARCHAR2(5)
;

--2-4

ALTER TABLE EMP_USER 
	MODIFY SUR_NAME VARCHAR2(10)
;

--2-5
ALTER TABLE EMP_USER
	RENAME COLUMN ENAME TO FULL_NAME
;


-- 3-1
CREATE TABLE EMP_IDX (
  EMPNO NUMBER(4) CONSTRAINT PK_EMP_IDX PRIMARY KEY,
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  DEPTNO NUMBER(2),
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
);

CREATE INDEX EMP_EMPNO_IDX
ON EMP_IDX(EMPNO);

-- 3-2

SELECT *
FROM User_Indexes
WHERE Index_Name = 'EMP_EMPNO_IDX';

-- 3-3

CREATE OR REPLACE VIEW emp_view AS
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE,
       SAL, NVL2(COMM, 'Y', 'N') AS COMM
FROM EMP_IDX
WHERE SAL >= 20000;


-- 4
/*
 * 1. 제약조건 
 * 2. 고유제약조건 
 * 3. NOT NULL 
 * 4. PK제약조건 
 * 5. FK(외래키)
 */