SELECT * FROM EMP;

SELECT ename
	FROM EMP 
		WHERE deptno = '20';
		
SELECT ename, job, sal, deptno
	FROM EMP e 
	WHERE deptno = 20
		AND job = 'analyst;'
		

SELECT *
	FROM EMP e 	
	WHERE sal > 2500
	ORDER BY sal;
	
SELECT *
	FROM EMP e 	
	WHERE ename >= 'M'
	ORDER BY ename;
	
SELECT *
	FROM EMP e 	
	WHERE sal = 5000;
	
SELECT *
	FROM EMP e 	
	WHERE sal != 5000;

SELECT *
	FROM EMP e 	
	WHERE sal <> 5000;

SELECT *
	FROM EMP e 	
	WHERE sal ^= 5000;

SELECT *
	FROM EMP e 	
	WHERE NOT sal = 5000;


SELECT * FROM EMP e 
	WHERE sal = (SELECT MAX(sal)
		FROM EMP);
	
	
SELECT *
	FROM EMP e 
	WHERE ename LIKE 'M%';

SELECT *
	FROM EMP e 
	WHERE ename LIKE '_L%';

SELECT *
	FROM EMP e 
	WHERE ename LIKE '%AM%';

SELECT *
	FROM EMP e 
	WHERE ename NOT LIKE '%S';


SELECT *
	FROM EMP e 	
	WHERE COMM IS NULL;
	
SELECT *
	FROM EMP e 	
	WHERE MGR = NULL;
	
SELECT emopno, ename, Sal, deptno, JOB 
	FROM EMP
	WHERE JOB 'CLERK';

UNION 

SELECT emopno, ename, Sal, deptno, JOB 
	FROM EMP
	WHERE JOB = 'SALESMAN';

SELECT EMPNO, ENAME, SAL
FROM EMP e 
WHERE DEPTNO = 10

UNION 
SELECT EMPNO, ENAME, SAL
FROM EMP, WHERE DEPTNO = 20;


SELECT empno, ename, sal, deptno
	FROM EMP e 
	WHERE deptno = 10
	UNION ALL 
	SELECT empno, ename, sal, DEPTNO
	FROM EMP 
	WHERE DEPTNO = 10;
	

SELECT *
	FROM v$sqlfn_metadata;
	
SELECT ename, UPPER(ename), LOWER(ename), INITCAP(ename)
	FROM EMP;

-- LENGTH 문자열 길이
SELECT ename, LENGTH(ename) 
	FROM emp;

SELECT JOB
	,SUBSTR(jOb, 1, 2), SUBSTR(job, 3, 2), SUBSTR(job, 5)
	FROM emp;

SELECT job, SUBSTR(job, -LENGTH(job)), SUBSTR(job, -LENGTH(job), 2),
	SUBSTR(job, -3)	
	FROM emp;

-- 'S' 가 포함된 이름의 직원
SELECT * FROM EMP e 	
	WHERE INSTR(ename, 'S') > 0;
	
SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR_1
	, INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR_2
	, INSTR('HELLO, ORACLE!', 'L', 2, 2) AS INSTR_3
FROM DUAL;

SELECT '010-1234-5678' AS REPLACE_BEFORE
	,REPLACE('010-1234-5678', '-', '')AS REPLACE_1
	,REPLACE('010-1234-5678', '-')AS REPLACE_2
FROM DUAL;


SELECT 'ORACLE', LPAD('ORACLE', 10, '#') AS LPAD_1
	,RPAD('ORACLE', 10, '*') AS RPAD_1
	,LPAD('ORACLE', 10) AS LPAD_2
	,RPAD('ORACLE', 10) AS RPAD_2
FROM DUAL;

SELECT RPAD('971225-', 14, '*') AS RPAD_JMNO
	,RPAD('010-1234-', 13, '*') AS RPAD_PHONE
FROM DUAL;

SELECT empno, ename, concat(empno, ename),
	CONCAT(empno, CONCAT(':', ENAME))
FROM EMP e 
WHERE ename = 'SMITH';


SELECT '[' ||TRIM ('_ _Oracle_ _')||']' AS TRIM,
'[' ||TRIM(LEADING FROM'_ _Oracle_ _')||']' AS TRIM_LEADING,
'[' ||TRIM(TRAILING FROM'_ _Oracle_ _')||']' AS TRIM_TRAILING,
'[' ||TRIM(BOTH FROM'_ _Oracle_ _')||']' AS TRIM_BOTH
FROM DUAL;


SELECT '[' ||TRIM ('_Oracle_')||']' AS TRIM,
'[' ||LTRIM('_Oracle_')||']' AS LTRIM,
'[' ||LTRIM('<_Oracle_>', '_<')||']' AS LTRIM_2,
'[' ||RTRIM('_Oracle_')||']' AS RTRIM,
'[' ||RTRIM('<_Oracle_>', '>_')||']' AS RTRIM_2,
FROM DUAL;


SELECT SYSDATE AS NOW
	,SYSDATE-1 AS YESTERDAY
	, SYSDATE +1 AS TOMORROW
FROM DUAL;


SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3)
FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE,
	ADD_MONTHS(HIREDATE, 12*20) AS WORK10YEAR
FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, SYSDATE 
	FROM EMP 
	WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;

SELECT ENAME, HIREDATE, SYSDATE 
	,MONTHS_BETWEEN(HIREDATE, SYSDATE)/12 AS YEAR1
	,MONTHS_BETWEEN(SYSDATE, HIREDATE)/12 AS YEAR2
	,TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) AS YEAR3
FROM EMP;

SELECT SYSDATE,
	NEXT_DAY(SYSDATE, '월요일'),
	LAST_DAY(SYSDATE)
FROM DUAL;

SELECT ENAME
	,EXTRACT(YEAR FROM HIREDATE) AS y
	,EXTRACT(MONTH FROM HIREDATE) AS m
	,EXTRACT(DAY FROM HIREDATE) AS d
FROM emp;

-- 날짜에 ROUND 반올림 함수
SELECT SYSDATE, ROUND(SYSDATE, 'CC') AS FORMAT_CC,
	ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY,
	ROUND(SYSDATE, 'Q') AS FORMAT_Q,
	ROUND(SYSDATE, 'DDD')AS FORMAT_DDD,
	ROUND(SYSDATE, 'HH') AS FORMAT_HH
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS')AS current_datetime
FROM DUAL;

SELECT SYSDATE 
	,TO_CHAR(SYSDATE, 'MM') AS MM 
	,TO_CHAR(SYSDATE, 'MON') AS MON
	,TO_CHAR(SYSDATE, 'MONTH') AS MONTH
	,TO_CHAR(SYSDATE, 'DD') AS DD 
	,TO_CHAR(SYSDATE, 'DY') AS DY 
	,TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;

SELECT SYSDATE 
	, TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS
	, TO_CHAR(SYSDATE, 'HH12:MI:SS AM') S HHMISS_AM
	, TO_CHAR(SYSDATE, 'HH:MI:SS P.M.') AS HHMISS_PM
FROM DUAL;

SELECT TO_NUMBER('3,300', '999,999') -TO_NUMBER('1,100', '999,999')
FROM DUAL;

SELECT TO_DATE('2023-02-15', 'YYYY-MM-DD') AS TODATE1
	, TO_DATE('20150101', 'YYYY-MM-DD')AS TODATE2
FROM DUAL;

/* NULL 값 처리가 중요한 이유
 * NULL은 추정이 불가능한 특수한 값으로 연산, 비교 등이 불가
 */

SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM
	,NVL(COMM, 0)
	,SAL + NVL(COMM,0)
FROM EMP;

SELECT EMPNO, ENAME, COMM
	,NVL2(COMM, 'O', 'X')
	,NVL2(COMM, SAL*12 + COMM, SAL*12) AS ANNSAL
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL
	,DECODE(JOB,
		'MANAGER', SAL*0.2,
		'SALESMAN', SAL*0.3,
		'ANALYST', SAL*0.05,
		SAL*0.1) AS BONUS
FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL
	,CASE JOB 	
			WHEN 'MANAGER' THEN SAL*0.2
			WHEN 'SALESMAN' THEN SAL*0.3
			WHEN'ANALYST' THEN SAL*0.05
			ELSE SAL*0.1
			END AS BONUS
FROM EMP;

SELECT EMPNO, ENAME, COMM
	, CASE 
			WHEN COMM IS NULL THEN ''
			WHEN COMM = 0 THEN 'ZERO'
			WHEN COMM > 0 THEN 'Amount : || COMM'
			END AS SUMMARY
	FROM EMP;

SELECT *
	FROM EMP, DEPT d
	WHERE EMP.DEPTNO = DEPT.DEPTNO 
	ORDER BY EMPNO;

SELECT *
	FROM EMP E JOIN DEPT D 
		ON (E.DEPTNO = D.DEPTNO)
	ORDER BY EMPNO;

SELECT *
FROM EMP E JOIN DEPT D 	
	USING (DEPTNO)
ORDER BY E.EMPNO;
	




